server:
    log_level: info
metrics:
    global:
        scrape_interval: 15s
        external_labels:
            project_id: 13-kscvp1e-metrics
            project_name: Harold-i7ovh-metrics
        remote_write:
            - url: http://telescope.blockops.network
              basic_auth:
                password: hUhkjyHGyyKB
                username: thanos-bl-receiver
    wal_directory: /tmp/wal
    configs:
        - name: 0hxnetworkethereum_metrics
          host_filter: false
          scrape_configs:
            - job_name: 0hxnetwork_ethereum_execution_job_0
              static_configs:
                - targets:
                    - localhost:6060
            - job_name: 0hxnetwork_ethereum_consensus_job_1
              static_configs:
                - targets:
                    - localhost:8008
logs:
    configs:
        - name: telescope_logs
          clients:
            - url: https://logs.blockops.network
              basic_auth:
                username: user
                password: pass
              external_labels:
                project_id: adedayo123
                project_name: 0hxNEtwork
          positions:
            filename: /tmp/telescope_logs
integrations:
    agent:
        enabled: false
    node_exporter:
        enabled: true
