server:
  log_level: info
metrics:
  global:
    scrape_interval: 15s
    external_labels:
      project_id: blockops-ssv-2024
      project_name: blockops-ssv
    remote_write:
      - url: https://telescope.blockops.network
        basic_auth:
          password: blockops
          username: blockops
  wal_directory: /var/lib/telescope
  configs:
    - name: blockops-ssv_ssv_metrics
      host_filter: false
      scrape_configs:
        - job_name: blockops-ssv_ssv_ssv_job_0
          static_configs:
            - targets:
                - localhost:15000
        - job_name: blockops-ssv_ssv_execution_job_1
          static_configs:
            - targets:
                - localhost:6060
        - job_name: blockops-ssv_ssv_consensus_job_2
          static_configs:
            - targets:
                - localhost:8008
logs:
  configs: []
integrations:
  agent:
    enabled: false
  node_exporter:
    enabled: true
