apiVersion: v1
kind: Secret
metadata:
  name: telescope-secrets
type: Opaque
data:
  username: aHlwZXJicmlkZ2U=  # Base64 encoded 'hyperbridge'
  password: aHlwZXJicmlkZ2U=  # Base64 encoded 'hyperbridge'

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: telescope-config
data:
  TELES_CONFIG: "--metrics --network hyperbridge --project-id hyperbridge --project-name hyperbridge-paseo-collator --remote-write-url https://hyperbridge-prometheus.blockops.network/api/v1/write"
