name: CI

on:
    push:
      branches:
        - 'feature/**'
        - 'v[0-9]+.[0-9]+'
    pull_request:
      branches:
        - main
        - 'feature/**'
        - 'v[0-9]+.[0-9]+'

env:
  GO_VERSION: 1.22.1

concurrency: 
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.run_id }}
  cancel-in-progress: true

jobs:
  golangci:
    strategy:
      fail-fast: false
    name: Build and Push
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: ${{ env.GO_VERSION }}
      - name: Docker login
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Docker Build
        run: |
          make agent-image
      - name: Docker Push
        run: |
          make agent-push
      

            