name: Release

on:
  push:
    tags:
      - "v*"
  pull_request:
        branches:
            - main
  workflow_dispatch:    
jobs:
  # the workflow can contain other jobs, such as linting, testing, etc.
  release:
    runs-on: ubuntu-latest
    steps:
      # run git checkout
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # setup go
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.22.1

      # run goreleaser
      - name: Run GoReleaser
        # if: github.ref == 'refs/heads/main' && ( github.event_name == 'push' || github.event_name == 'workflow_dispatch' )
        uses: goreleaser/goreleaser-action@v4
        with:
          version: latest
          args: release --clean
          distribution: goreleaser
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
