name: Docker Latest tag For Releases

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag of the base image to use'
        required: true
        type: string
      new_tag:
        description: 'New tag to use'
        default: 'latest'
        required: true
        type: string
      dry_run:
        description: "Don't push the tag to DockerHub"
        required: true
        type: boolean
        default: false

jobs:
  tag-docker-image:
    name: Retag image and push to DockerHub
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        with:
            platforms: all
  
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3    

      - name: Create builder
        run: docker buildx create --name mybuilder --use

      - name: Inspect builder
        run: docker buildx inspect --bootstrap

      - name: Pull the original image
        run: docker pull blockopsnetwork/telescope:${{ github.event.inputs.tag }}

      - name: Create new multi-arch image with new tag
        run: docker buildx imagetools create --tag blockopsnetwork/telescope:${{ github.event.inputs.new_tag }} blockopsnetwork/telescope:${{ github.event.inputs.tag }}
