# Re-tag the given image and push it to the DockerHub
# Preserves the old tag.
name: Docker Latest tag For Releases

# on:
#   workflow_dispatch:
#     inputs:
#       tag:
#         description: 'Tag of the base image to use'
#         required: true
#         type: string
#       new_tag:
#         description: 'New tag to use'
#         default: 'latest'
#         required: true
#         type: string
#       dry_run:
#         description: "Don't push the tag to Docker"
#         required: true
#         type: boolean
#         default: false

on:
    push:
      branches: [main]
      tags:
        - "*"
    merge_group:
    pull_request:
      branches:
        - main
        - 'feature/**'
        - 'v[0-9]+.[0-9]+'

jobs:
  tag-docker-image:
    name: Retag image and push to DockerHub
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        with:
            platforms: all
  
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3    

      - name: Re-tag image
        run: |
          docker pull blockopsnetwork/telescope:2024-06-24-1d0217f
          docker tag blockopsnetwork/telescope:2024-06-24-1d0217f blockopsnetwork/telescope:edge
          
      - name: Push image
        # if: ${{ !fromJSON(github.event.inputs.dry_run) }}
        run: |
          docker push blockopsnetwork/telescope:edge
